// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v5.29.3
// source: common/runtime/proto/topology.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TopologyService_Subscribe_FullMethodName      = "/aether.runtime.TopologyService/Subscribe"
	TopologyService_ListTopologies_FullMethodName = "/aether.runtime.TopologyService/ListTopologies"
)

// TopologyServiceClient is the client API for TopologyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// TopologyService 让 Runtime 订阅 Server 的 topology 意图
type TopologyServiceClient interface {
	// Subscribe 持续接收 topology 更新（server push）
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TopologyUpdate], error)
	// ListTopologies 获取全量 topology（用于 reconcile）
	ListTopologies(ctx context.Context, in *ListTopologiesRequest, opts ...grpc.CallOption) (*ListTopologiesResponse, error)
}

type topologyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTopologyServiceClient(cc grpc.ClientConnInterface) TopologyServiceClient {
	return &topologyServiceClient{cc}
}

func (c *topologyServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TopologyUpdate], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &TopologyService_ServiceDesc.Streams[0], TopologyService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, TopologyUpdate]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TopologyService_SubscribeClient = grpc.ServerStreamingClient[TopologyUpdate]

func (c *topologyServiceClient) ListTopologies(ctx context.Context, in *ListTopologiesRequest, opts ...grpc.CallOption) (*ListTopologiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTopologiesResponse)
	err := c.cc.Invoke(ctx, TopologyService_ListTopologies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TopologyServiceServer is the server API for TopologyService service.
// All implementations must embed UnimplementedTopologyServiceServer
// for forward compatibility.
//
// TopologyService 让 Runtime 订阅 Server 的 topology 意图
type TopologyServiceServer interface {
	// Subscribe 持续接收 topology 更新（server push）
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[TopologyUpdate]) error
	// ListTopologies 获取全量 topology（用于 reconcile）
	ListTopologies(context.Context, *ListTopologiesRequest) (*ListTopologiesResponse, error)
	mustEmbedUnimplementedTopologyServiceServer()
}

// UnimplementedTopologyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTopologyServiceServer struct{}

func (UnimplementedTopologyServiceServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[TopologyUpdate]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedTopologyServiceServer) ListTopologies(context.Context, *ListTopologiesRequest) (*ListTopologiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTopologies not implemented")
}
func (UnimplementedTopologyServiceServer) mustEmbedUnimplementedTopologyServiceServer() {}
func (UnimplementedTopologyServiceServer) testEmbeddedByValue()                         {}

// UnsafeTopologyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TopologyServiceServer will
// result in compilation errors.
type UnsafeTopologyServiceServer interface {
	mustEmbedUnimplementedTopologyServiceServer()
}

func RegisterTopologyServiceServer(s grpc.ServiceRegistrar, srv TopologyServiceServer) {
	// If the following call panics, it indicates UnimplementedTopologyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TopologyService_ServiceDesc, srv)
}

func _TopologyService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TopologyServiceServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, TopologyUpdate]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type TopologyService_SubscribeServer = grpc.ServerStreamingServer[TopologyUpdate]

func _TopologyService_ListTopologies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTopologiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TopologyServiceServer).ListTopologies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TopologyService_ListTopologies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TopologyServiceServer).ListTopologies(ctx, req.(*ListTopologiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TopologyService_ServiceDesc is the grpc.ServiceDesc for TopologyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TopologyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "aether.runtime.TopologyService",
	HandlerType: (*TopologyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListTopologies",
			Handler:    _TopologyService_ListTopologies_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _TopologyService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "common/runtime/proto/topology.proto",
}
