// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: common/runtime/proto/topology.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateType int32

const (
	UpdateType_FULL  UpdateType = 0
	UpdateType_PATCH UpdateType = 1
)

// Enum value maps for UpdateType.
var (
	UpdateType_name = map[int32]string{
		0: "FULL",
		1: "PATCH",
	}
	UpdateType_value = map[string]int32{
		"FULL":  0,
		"PATCH": 1,
	}
)

func (x UpdateType) Enum() *UpdateType {
	p := new(UpdateType)
	*p = x
	return p
}

func (x UpdateType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_runtime_proto_topology_proto_enumTypes[0].Descriptor()
}

func (UpdateType) Type() protoreflect.EnumType {
	return &file_common_runtime_proto_topology_proto_enumTypes[0]
}

func (x UpdateType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateType.Descriptor instead.
func (UpdateType) EnumDescriptor() ([]byte, []int) {
	return file_common_runtime_proto_topology_proto_rawDescGZIP(), []int{0}
}

type Connectivity int32

const (
	// 全互联，每两个节点之间直连
	Connectivity_MESH Connectivity = 0
	// 中心节点转发
	Connectivity_HUB_SPOKE Connectivity = 1
	// 点对点，只有 source ↔ target
	Connectivity_POINT_TO_POINT Connectivity = 2
)

// Enum value maps for Connectivity.
var (
	Connectivity_name = map[int32]string{
		0: "MESH",
		1: "HUB_SPOKE",
		2: "POINT_TO_POINT",
	}
	Connectivity_value = map[string]int32{
		"MESH":           0,
		"HUB_SPOKE":      1,
		"POINT_TO_POINT": 2,
	}
)

func (x Connectivity) Enum() *Connectivity {
	p := new(Connectivity)
	*p = x
	return p
}

func (x Connectivity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Connectivity) Descriptor() protoreflect.EnumDescriptor {
	return file_common_runtime_proto_topology_proto_enumTypes[1].Descriptor()
}

func (Connectivity) Type() protoreflect.EnumType {
	return &file_common_runtime_proto_topology_proto_enumTypes[1]
}

func (x Connectivity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Connectivity.Descriptor instead.
func (Connectivity) EnumDescriptor() ([]byte, []int) {
	return file_common_runtime_proto_topology_proto_rawDescGZIP(), []int{1}
}

type Exposure int32

const (
	// 仅 namespace 内部可见
	Exposure_INTERNAL Exposure = 0
	// 允许外部访问
	Exposure_EXTERNAL Exposure = 1
)

// Enum value maps for Exposure.
var (
	Exposure_name = map[int32]string{
		0: "INTERNAL",
		1: "EXTERNAL",
	}
	Exposure_value = map[string]int32{
		"INTERNAL": 0,
		"EXTERNAL": 1,
	}
)

func (x Exposure) Enum() *Exposure {
	p := new(Exposure)
	*p = x
	return p
}

func (x Exposure) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Exposure) Descriptor() protoreflect.EnumDescriptor {
	return file_common_runtime_proto_topology_proto_enumTypes[2].Descriptor()
}

func (Exposure) Type() protoreflect.EnumType {
	return &file_common_runtime_proto_topology_proto_enumTypes[2]
}

func (x Exposure) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Exposure.Descriptor instead.
func (Exposure) EnumDescriptor() ([]byte, []int) {
	return file_common_runtime_proto_topology_proto_rawDescGZIP(), []int{2}
}

type RelayPolicy int32

const (
	// Runtime 自行判断是否需要中继
	RelayPolicy_AUTO RelayPolicy = 0
	// 禁止中继，必须直连
	RelayPolicy_NEVER RelayPolicy = 1
	// 强制中继
	RelayPolicy_ALWAYS RelayPolicy = 2
)

// Enum value maps for RelayPolicy.
var (
	RelayPolicy_name = map[int32]string{
		0: "AUTO",
		1: "NEVER",
		2: "ALWAYS",
	}
	RelayPolicy_value = map[string]int32{
		"AUTO":   0,
		"NEVER":  1,
		"ALWAYS": 2,
	}
)

func (x RelayPolicy) Enum() *RelayPolicy {
	p := new(RelayPolicy)
	*p = x
	return p
}

func (x RelayPolicy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelayPolicy) Descriptor() protoreflect.EnumDescriptor {
	return file_common_runtime_proto_topology_proto_enumTypes[3].Descriptor()
}

func (RelayPolicy) Type() protoreflect.EnumType {
	return &file_common_runtime_proto_topology_proto_enumTypes[3]
}

func (x RelayPolicy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelayPolicy.Descriptor instead.
func (RelayPolicy) EnumDescriptor() ([]byte, []int) {
	return file_common_runtime_proto_topology_proto_rawDescGZIP(), []int{3}
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuntimeId     string                 `protobuf:"bytes,1,opt,name=runtime_id,json=runtimeId,proto3" json:"runtime_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_common_runtime_proto_topology_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_runtime_proto_topology_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_common_runtime_proto_topology_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetRuntimeId() string {
	if x != nil {
		return x.RuntimeId
	}
	return ""
}

type ListTopologiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTopologiesRequest) Reset() {
	*x = ListTopologiesRequest{}
	mi := &file_common_runtime_proto_topology_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopologiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopologiesRequest) ProtoMessage() {}

func (x *ListTopologiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_runtime_proto_topology_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopologiesRequest.ProtoReflect.Descriptor instead.
func (*ListTopologiesRequest) Descriptor() ([]byte, []int) {
	return file_common_runtime_proto_topology_proto_rawDescGZIP(), []int{1}
}

type ListTopologiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topologies    []*Topology            `protobuf:"bytes,1,rep,name=topologies,proto3" json:"topologies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTopologiesResponse) Reset() {
	*x = ListTopologiesResponse{}
	mi := &file_common_runtime_proto_topology_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopologiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopologiesResponse) ProtoMessage() {}

func (x *ListTopologiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_runtime_proto_topology_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopologiesResponse.ProtoReflect.Descriptor instead.
func (*ListTopologiesResponse) Descriptor() ([]byte, []int) {
	return file_common_runtime_proto_topology_proto_rawDescGZIP(), []int{2}
}

func (x *ListTopologiesResponse) GetTopologies() []*Topology {
	if x != nil {
		return x.Topologies
	}
	return nil
}

type TopologyUpdate struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Type       UpdateType             `protobuf:"varint,1,opt,name=type,proto3,enum=bbgrid.runtime.UpdateType" json:"type,omitempty"`
	Topologies []*Topology            `protobuf:"bytes,2,rep,name=topologies,proto3" json:"topologies,omitempty"`
	// 被删除的 namespace 列表（仅 patch 时有意义）
	DeletedNamespaces []string `protobuf:"bytes,3,rep,name=deleted_namespaces,json=deletedNamespaces,proto3" json:"deleted_namespaces,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TopologyUpdate) Reset() {
	*x = TopologyUpdate{}
	mi := &file_common_runtime_proto_topology_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TopologyUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TopologyUpdate) ProtoMessage() {}

func (x *TopologyUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_common_runtime_proto_topology_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TopologyUpdate.ProtoReflect.Descriptor instead.
func (*TopologyUpdate) Descriptor() ([]byte, []int) {
	return file_common_runtime_proto_topology_proto_rawDescGZIP(), []int{3}
}

func (x *TopologyUpdate) GetType() UpdateType {
	if x != nil {
		return x.Type
	}
	return UpdateType_FULL
}

func (x *TopologyUpdate) GetTopologies() []*Topology {
	if x != nil {
		return x.Topologies
	}
	return nil
}

func (x *TopologyUpdate) GetDeletedNamespaces() []string {
	if x != nil {
		return x.DeletedNamespaces
	}
	return nil
}

// Topology 一个 namespace 的连接意图
//
// Server 只描述"应该形成怎样的连接关系"，
// Runtime 自己决定"如何建立连接"。
type Topology struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Intent        *Intent                `protobuf:"bytes,2,opt,name=intent,proto3" json:"intent,omitempty"`
	Members       []*Member              `protobuf:"bytes,3,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topology) Reset() {
	*x = Topology{}
	mi := &file_common_runtime_proto_topology_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topology) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topology) ProtoMessage() {}

func (x *Topology) ProtoReflect() protoreflect.Message {
	mi := &file_common_runtime_proto_topology_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topology.ProtoReflect.Descriptor instead.
func (*Topology) Descriptor() ([]byte, []int) {
	return file_common_runtime_proto_topology_proto_rawDescGZIP(), []int{4}
}

func (x *Topology) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Topology) GetIntent() *Intent {
	if x != nil {
		return x.Intent
	}
	return nil
}

func (x *Topology) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

// Intent 连接意图
type Intent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 连接拓扑
	Connectivity Connectivity `protobuf:"varint,1,opt,name=connectivity,proto3,enum=bbgrid.runtime.Connectivity" json:"connectivity,omitempty"`
	// 暴露级别
	Exposure Exposure `protobuf:"varint,2,opt,name=exposure,proto3,enum=bbgrid.runtime.Exposure" json:"exposure,omitempty"`
	// 中继策略
	RelayPolicy   RelayPolicy `protobuf:"varint,3,opt,name=relay_policy,json=relayPolicy,proto3,enum=bbgrid.runtime.RelayPolicy" json:"relay_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Intent) Reset() {
	*x = Intent{}
	mi := &file_common_runtime_proto_topology_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Intent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Intent) ProtoMessage() {}

func (x *Intent) ProtoReflect() protoreflect.Message {
	mi := &file_common_runtime_proto_topology_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Intent.ProtoReflect.Descriptor instead.
func (*Intent) Descriptor() ([]byte, []int) {
	return file_common_runtime_proto_topology_proto_rawDescGZIP(), []int{5}
}

func (x *Intent) GetConnectivity() Connectivity {
	if x != nil {
		return x.Connectivity
	}
	return Connectivity_MESH
}

func (x *Intent) GetExposure() Exposure {
	if x != nil {
		return x.Exposure
	}
	return Exposure_INTERNAL
}

func (x *Intent) GetRelayPolicy() RelayPolicy {
	if x != nil {
		return x.RelayPolicy
	}
	return RelayPolicy_AUTO
}

// Member namespace 中的一个成员
type Member struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	ClientId string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	// 角色：source / target / peer
	Role          string `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_common_runtime_proto_topology_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_common_runtime_proto_topology_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_common_runtime_proto_topology_proto_rawDescGZIP(), []int{6}
}

func (x *Member) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *Member) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

var File_common_runtime_proto_topology_proto protoreflect.FileDescriptor

const file_common_runtime_proto_topology_proto_rawDesc = "" +
	"\n" +
	"#common/runtime/proto/topology.proto\x12\x0ebbgrid.runtime\"1\n" +
	"\x10SubscribeRequest\x12\x1d\n" +
	"\n" +
	"runtime_id\x18\x01 \x01(\tR\truntimeId\"\x17\n" +
	"\x15ListTopologiesRequest\"R\n" +
	"\x16ListTopologiesResponse\x128\n" +
	"\n" +
	"topologies\x18\x01 \x03(\v2\x18.bbgrid.runtime.TopologyR\n" +
	"topologies\"\xa9\x01\n" +
	"\x0eTopologyUpdate\x12.\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1a.bbgrid.runtime.UpdateTypeR\x04type\x128\n" +
	"\n" +
	"topologies\x18\x02 \x03(\v2\x18.bbgrid.runtime.TopologyR\n" +
	"topologies\x12-\n" +
	"\x12deleted_namespaces\x18\x03 \x03(\tR\x11deletedNamespaces\"\x8a\x01\n" +
	"\bTopology\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12.\n" +
	"\x06intent\x18\x02 \x01(\v2\x16.bbgrid.runtime.IntentR\x06intent\x120\n" +
	"\amembers\x18\x03 \x03(\v2\x16.bbgrid.runtime.MemberR\amembers\"\xc0\x01\n" +
	"\x06Intent\x12@\n" +
	"\fconnectivity\x18\x01 \x01(\x0e2\x1c.bbgrid.runtime.ConnectivityR\fconnectivity\x124\n" +
	"\bexposure\x18\x02 \x01(\x0e2\x18.bbgrid.runtime.ExposureR\bexposure\x12>\n" +
	"\frelay_policy\x18\x03 \x01(\x0e2\x1b.bbgrid.runtime.RelayPolicyR\vrelayPolicy\"9\n" +
	"\x06Member\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role*!\n" +
	"\n" +
	"UpdateType\x12\b\n" +
	"\x04FULL\x10\x00\x12\t\n" +
	"\x05PATCH\x10\x01*;\n" +
	"\fConnectivity\x12\b\n" +
	"\x04MESH\x10\x00\x12\r\n" +
	"\tHUB_SPOKE\x10\x01\x12\x12\n" +
	"\x0ePOINT_TO_POINT\x10\x02*&\n" +
	"\bExposure\x12\f\n" +
	"\bINTERNAL\x10\x00\x12\f\n" +
	"\bEXTERNAL\x10\x01*.\n" +
	"\vRelayPolicy\x12\b\n" +
	"\x04AUTO\x10\x00\x12\t\n" +
	"\x05NEVER\x10\x01\x12\n" +
	"\n" +
	"\x06ALWAYS\x10\x022\xc3\x01\n" +
	"\x0fTopologyService\x12O\n" +
	"\tSubscribe\x12 .bbgrid.runtime.SubscribeRequest\x1a\x1e.bbgrid.runtime.TopologyUpdate0\x01\x12_\n" +
	"\x0eListTopologies\x12%.bbgrid.runtime.ListTopologiesRequest\x1a&.bbgrid.runtime.ListTopologiesResponseB\x1aZ\x18BBgrid/common/runtime/pbb\x06proto3"

var (
	file_common_runtime_proto_topology_proto_rawDescOnce sync.Once
	file_common_runtime_proto_topology_proto_rawDescData []byte
)

func file_common_runtime_proto_topology_proto_rawDescGZIP() []byte {
	file_common_runtime_proto_topology_proto_rawDescOnce.Do(func() {
		file_common_runtime_proto_topology_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_runtime_proto_topology_proto_rawDesc), len(file_common_runtime_proto_topology_proto_rawDesc)))
	})
	return file_common_runtime_proto_topology_proto_rawDescData
}

var file_common_runtime_proto_topology_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_common_runtime_proto_topology_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_common_runtime_proto_topology_proto_goTypes = []any{
	(UpdateType)(0),                // 0: bbgrid.runtime.UpdateType
	(Connectivity)(0),              // 1: bbgrid.runtime.Connectivity
	(Exposure)(0),                  // 2: bbgrid.runtime.Exposure
	(RelayPolicy)(0),               // 3: bbgrid.runtime.RelayPolicy
	(*SubscribeRequest)(nil),       // 4: bbgrid.runtime.SubscribeRequest
	(*ListTopologiesRequest)(nil),  // 5: bbgrid.runtime.ListTopologiesRequest
	(*ListTopologiesResponse)(nil), // 6: bbgrid.runtime.ListTopologiesResponse
	(*TopologyUpdate)(nil),         // 7: bbgrid.runtime.TopologyUpdate
	(*Topology)(nil),               // 8: bbgrid.runtime.Topology
	(*Intent)(nil),                 // 9: bbgrid.runtime.Intent
	(*Member)(nil),                 // 10: bbgrid.runtime.Member
}
var file_common_runtime_proto_topology_proto_depIdxs = []int32{
	8,  // 0: bbgrid.runtime.ListTopologiesResponse.topologies:type_name -> bbgrid.runtime.Topology
	0,  // 1: bbgrid.runtime.TopologyUpdate.type:type_name -> bbgrid.runtime.UpdateType
	8,  // 2: bbgrid.runtime.TopologyUpdate.topologies:type_name -> bbgrid.runtime.Topology
	9,  // 3: bbgrid.runtime.Topology.intent:type_name -> bbgrid.runtime.Intent
	10, // 4: bbgrid.runtime.Topology.members:type_name -> bbgrid.runtime.Member
	1,  // 5: bbgrid.runtime.Intent.connectivity:type_name -> bbgrid.runtime.Connectivity
	2,  // 6: bbgrid.runtime.Intent.exposure:type_name -> bbgrid.runtime.Exposure
	3,  // 7: bbgrid.runtime.Intent.relay_policy:type_name -> bbgrid.runtime.RelayPolicy
	4,  // 8: bbgrid.runtime.TopologyService.Subscribe:input_type -> bbgrid.runtime.SubscribeRequest
	5,  // 9: bbgrid.runtime.TopologyService.ListTopologies:input_type -> bbgrid.runtime.ListTopologiesRequest
	7,  // 10: bbgrid.runtime.TopologyService.Subscribe:output_type -> bbgrid.runtime.TopologyUpdate
	6,  // 11: bbgrid.runtime.TopologyService.ListTopologies:output_type -> bbgrid.runtime.ListTopologiesResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_common_runtime_proto_topology_proto_init() }
func file_common_runtime_proto_topology_proto_init() {
	if File_common_runtime_proto_topology_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_runtime_proto_topology_proto_rawDesc), len(file_common_runtime_proto_topology_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_runtime_proto_topology_proto_goTypes,
		DependencyIndexes: file_common_runtime_proto_topology_proto_depIdxs,
		EnumInfos:         file_common_runtime_proto_topology_proto_enumTypes,
		MessageInfos:      file_common_runtime_proto_topology_proto_msgTypes,
	}.Build()
	File_common_runtime_proto_topology_proto = out.File
	file_common_runtime_proto_topology_proto_goTypes = nil
	file_common_runtime_proto_topology_proto_depIdxs = nil
}
