// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: common/plugin/proto/plugin.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 插件标识
	PluginId string `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	// 订阅的资源类型（空 = 全部）
	ResourceTypes []string `protobuf:"bytes,2,rep,name=resource_types,json=resourceTypes,proto3" json:"resource_types,omitempty"`
	// 订阅的事件类型（空 = 全部）
	EventTypes    []string `protobuf:"bytes,3,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_common_plugin_proto_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_plugin_proto_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_common_plugin_proto_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *SubscribeRequest) GetResourceTypes() []string {
	if x != nil {
		return x.ResourceTypes
	}
	return nil
}

func (x *SubscribeRequest) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

type EventBatch struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Events []*PluginEvent         `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	// 执行请求（Server → 插件）
	ExecuteRequests []*ExecuteRequest `protobuf:"bytes,2,rep,name=execute_requests,json=executeRequests,proto3" json:"execute_requests,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EventBatch) Reset() {
	*x = EventBatch{}
	mi := &file_common_plugin_proto_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventBatch) ProtoMessage() {}

func (x *EventBatch) ProtoReflect() protoreflect.Message {
	mi := &file_common_plugin_proto_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventBatch.ProtoReflect.Descriptor instead.
func (*EventBatch) Descriptor() ([]byte, []int) {
	return file_common_plugin_proto_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *EventBatch) GetEvents() []*PluginEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *EventBatch) GetExecuteRequests() []*ExecuteRequest {
	if x != nil {
		return x.ExecuteRequests
	}
	return nil
}

type PluginEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 事件 ID
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// 事件序列号
	Sequence int64 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// 时间戳（毫秒）
	Timestamp int64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// 资源标识
	Resource *ResourceKey `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
	// 事件类型：ADDED, MODIFIED, DELETED
	EventType string `protobuf:"bytes,5,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	// 业务数据（JSON 编码）
	Payload       []byte `protobuf:"bytes,6,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginEvent) Reset() {
	*x = PluginEvent{}
	mi := &file_common_plugin_proto_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginEvent) ProtoMessage() {}

func (x *PluginEvent) ProtoReflect() protoreflect.Message {
	mi := &file_common_plugin_proto_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginEvent.ProtoReflect.Descriptor instead.
func (*PluginEvent) Descriptor() ([]byte, []int) {
	return file_common_plugin_proto_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *PluginEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PluginEvent) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *PluginEvent) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PluginEvent) GetResource() *ResourceKey {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *PluginEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *PluginEvent) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type ResourceKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceKey) Reset() {
	*x = ResourceKey{}
	mi := &file_common_plugin_proto_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceKey) ProtoMessage() {}

func (x *ResourceKey) ProtoReflect() protoreflect.Message {
	mi := &file_common_plugin_proto_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceKey.ProtoReflect.Descriptor instead.
func (*ResourceKey) Descriptor() ([]byte, []int) {
	return file_common_plugin_proto_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ResourceKey) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResourceKey) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ResourceKey) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PublishRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Events        []*PluginEvent         `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_common_plugin_proto_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_plugin_proto_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_common_plugin_proto_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *PublishRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *PublishRequest) GetEvents() []*PluginEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type PublishResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_common_plugin_proto_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_plugin_proto_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_common_plugin_proto_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *PublishResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PublishResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 插件标识
	PluginId string `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	// 插件版本
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// 能力声明
	Capabilities []*Capability `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Action 声明
	Actions       []*ActionDeclaration `protobuf:"bytes,4,rep,name=actions,proto3" json:"actions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_common_plugin_proto_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_plugin_proto_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_common_plugin_proto_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *RegisterRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *RegisterRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterRequest) GetCapabilities() []*Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *RegisterRequest) GetActions() []*ActionDeclaration {
	if x != nil {
		return x.Actions
	}
	return nil
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_common_plugin_proto_plugin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_plugin_proto_plugin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_common_plugin_proto_plugin_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Capability struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 资源类型
	ResourceType string `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	// 事件类型过滤（空 = 全部）
	EventTypes []string `protobuf:"bytes,2,rep,name=event_types,json=eventTypes,proto3" json:"event_types,omitempty"`
	// 描述
	Description   string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Capability) Reset() {
	*x = Capability{}
	mi := &file_common_plugin_proto_plugin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Capability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capability) ProtoMessage() {}

func (x *Capability) ProtoReflect() protoreflect.Message {
	mi := &file_common_plugin_proto_plugin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Capability.ProtoReflect.Descriptor instead.
func (*Capability) Descriptor() ([]byte, []int) {
	return file_common_plugin_proto_plugin_proto_rawDescGZIP(), []int{8}
}

func (x *Capability) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *Capability) GetEventTypes() []string {
	if x != nil {
		return x.EventTypes
	}
	return nil
}

func (x *Capability) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ActionDeclaration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Action 名称
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// 描述
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// 参数定义（JSON Schema）
	ParamsSchema  []byte `protobuf:"bytes,3,opt,name=params_schema,json=paramsSchema,proto3" json:"params_schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActionDeclaration) Reset() {
	*x = ActionDeclaration{}
	mi := &file_common_plugin_proto_plugin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActionDeclaration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionDeclaration) ProtoMessage() {}

func (x *ActionDeclaration) ProtoReflect() protoreflect.Message {
	mi := &file_common_plugin_proto_plugin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionDeclaration.ProtoReflect.Descriptor instead.
func (*ActionDeclaration) Descriptor() ([]byte, []int) {
	return file_common_plugin_proto_plugin_proto_rawDescGZIP(), []int{9}
}

func (x *ActionDeclaration) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActionDeclaration) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ActionDeclaration) GetParamsSchema() []byte {
	if x != nil {
		return x.ParamsSchema
	}
	return nil
}

type ExecuteRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Action 名称
	Action string `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
	// 参数（JSON 编码）
	Params        []byte `protobuf:"bytes,2,opt,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_common_plugin_proto_plugin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_plugin_proto_plugin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_common_plugin_proto_plugin_proto_rawDescGZIP(), []int{10}
}

func (x *ExecuteRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ExecuteRequest) GetParams() []byte {
	if x != nil {
		return x.Params
	}
	return nil
}

type ExecuteResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Success bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// 结果（JSON 编码）
	Result        []byte `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_common_plugin_proto_plugin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_plugin_proto_plugin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_common_plugin_proto_plugin_proto_rawDescGZIP(), []int{11}
}

func (x *ExecuteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteResponse) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ExecuteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_common_plugin_proto_plugin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_plugin_proto_plugin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_common_plugin_proto_plugin_proto_rawDescGZIP(), []int{12}
}

func (x *HeartbeatRequest) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *HeartbeatRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerTime    int64                  `protobuf:"varint,1,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_common_plugin_proto_plugin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_plugin_proto_plugin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_common_plugin_proto_plugin_proto_rawDescGZIP(), []int{13}
}

func (x *HeartbeatResponse) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

var File_common_plugin_proto_plugin_proto protoreflect.FileDescriptor

const file_common_plugin_proto_plugin_proto_rawDesc = "" +
	"\n" +
	" common/plugin/proto/plugin.proto\x12\rbbgrid.plugin\"w\n" +
	"\x10SubscribeRequest\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12%\n" +
	"\x0eresource_types\x18\x02 \x03(\tR\rresourceTypes\x12\x1f\n" +
	"\vevent_types\x18\x03 \x03(\tR\n" +
	"eventTypes\"\x8a\x01\n" +
	"\n" +
	"EventBatch\x122\n" +
	"\x06events\x18\x01 \x03(\v2\x1a.bbgrid.plugin.PluginEventR\x06events\x12H\n" +
	"\x10execute_requests\x18\x02 \x03(\v2\x1d.bbgrid.plugin.ExecuteRequestR\x0fexecuteRequests\"\xc8\x01\n" +
	"\vPluginEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x03R\bsequence\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x126\n" +
	"\bresource\x18\x04 \x01(\v2\x1a.bbgrid.plugin.ResourceKeyR\bresource\x12\x1d\n" +
	"\n" +
	"event_type\x18\x05 \x01(\tR\teventType\x12\x18\n" +
	"\apayload\x18\x06 \x01(\fR\apayload\"S\n" +
	"\vResourceKey\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"a\n" +
	"\x0ePublishRequest\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x122\n" +
	"\x06events\x18\x02 \x03(\v2\x1a.bbgrid.plugin.PluginEventR\x06events\"A\n" +
	"\x0fPublishResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\xc3\x01\n" +
	"\x0fRegisterRequest\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12=\n" +
	"\fcapabilities\x18\x03 \x03(\v2\x19.bbgrid.plugin.CapabilityR\fcapabilities\x12:\n" +
	"\aactions\x18\x04 \x03(\v2 .bbgrid.plugin.ActionDeclarationR\aactions\"B\n" +
	"\x10RegisterResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"t\n" +
	"\n" +
	"Capability\x12#\n" +
	"\rresource_type\x18\x01 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vevent_types\x18\x02 \x03(\tR\n" +
	"eventTypes\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"n\n" +
	"\x11ActionDeclaration\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12#\n" +
	"\rparams_schema\x18\x03 \x01(\fR\fparamsSchema\"@\n" +
	"\x0eExecuteRequest\x12\x16\n" +
	"\x06action\x18\x01 \x01(\tR\x06action\x12\x16\n" +
	"\x06params\x18\x02 \x01(\fR\x06params\"Y\n" +
	"\x0fExecuteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06result\x18\x02 \x01(\fR\x06result\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"M\n" +
	"\x10HeartbeatRequest\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"4\n" +
	"\x11HeartbeatResponse\x12\x1f\n" +
	"\vserver_time\x18\x01 \x01(\x03R\n" +
	"serverTime2\x8b\x03\n" +
	"\rPluginService\x12I\n" +
	"\tSubscribe\x12\x1f.bbgrid.plugin.SubscribeRequest\x1a\x19.bbgrid.plugin.EventBatch0\x01\x12H\n" +
	"\aPublish\x12\x1d.bbgrid.plugin.PublishRequest\x1a\x1e.bbgrid.plugin.PublishResponse\x12K\n" +
	"\bRegister\x12\x1e.bbgrid.plugin.RegisterRequest\x1a\x1f.bbgrid.plugin.RegisterResponse\x12H\n" +
	"\aExecute\x12\x1d.bbgrid.plugin.ExecuteRequest\x1a\x1e.bbgrid.plugin.ExecuteResponse\x12N\n" +
	"\tHeartbeat\x12\x1f.bbgrid.plugin.HeartbeatRequest\x1a .bbgrid.plugin.HeartbeatResponseB\x1fZ\x1dBBgrid/common/plugin/proto/pbb\x06proto3"

var (
	file_common_plugin_proto_plugin_proto_rawDescOnce sync.Once
	file_common_plugin_proto_plugin_proto_rawDescData []byte
)

func file_common_plugin_proto_plugin_proto_rawDescGZIP() []byte {
	file_common_plugin_proto_plugin_proto_rawDescOnce.Do(func() {
		file_common_plugin_proto_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_plugin_proto_plugin_proto_rawDesc), len(file_common_plugin_proto_plugin_proto_rawDesc)))
	})
	return file_common_plugin_proto_plugin_proto_rawDescData
}

var file_common_plugin_proto_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_common_plugin_proto_plugin_proto_goTypes = []any{
	(*SubscribeRequest)(nil),  // 0: bbgrid.plugin.SubscribeRequest
	(*EventBatch)(nil),        // 1: bbgrid.plugin.EventBatch
	(*PluginEvent)(nil),       // 2: bbgrid.plugin.PluginEvent
	(*ResourceKey)(nil),       // 3: bbgrid.plugin.ResourceKey
	(*PublishRequest)(nil),    // 4: bbgrid.plugin.PublishRequest
	(*PublishResponse)(nil),   // 5: bbgrid.plugin.PublishResponse
	(*RegisterRequest)(nil),   // 6: bbgrid.plugin.RegisterRequest
	(*RegisterResponse)(nil),  // 7: bbgrid.plugin.RegisterResponse
	(*Capability)(nil),        // 8: bbgrid.plugin.Capability
	(*ActionDeclaration)(nil), // 9: bbgrid.plugin.ActionDeclaration
	(*ExecuteRequest)(nil),    // 10: bbgrid.plugin.ExecuteRequest
	(*ExecuteResponse)(nil),   // 11: bbgrid.plugin.ExecuteResponse
	(*HeartbeatRequest)(nil),  // 12: bbgrid.plugin.HeartbeatRequest
	(*HeartbeatResponse)(nil), // 13: bbgrid.plugin.HeartbeatResponse
}
var file_common_plugin_proto_plugin_proto_depIdxs = []int32{
	2,  // 0: bbgrid.plugin.EventBatch.events:type_name -> bbgrid.plugin.PluginEvent
	10, // 1: bbgrid.plugin.EventBatch.execute_requests:type_name -> bbgrid.plugin.ExecuteRequest
	3,  // 2: bbgrid.plugin.PluginEvent.resource:type_name -> bbgrid.plugin.ResourceKey
	2,  // 3: bbgrid.plugin.PublishRequest.events:type_name -> bbgrid.plugin.PluginEvent
	8,  // 4: bbgrid.plugin.RegisterRequest.capabilities:type_name -> bbgrid.plugin.Capability
	9,  // 5: bbgrid.plugin.RegisterRequest.actions:type_name -> bbgrid.plugin.ActionDeclaration
	0,  // 6: bbgrid.plugin.PluginService.Subscribe:input_type -> bbgrid.plugin.SubscribeRequest
	4,  // 7: bbgrid.plugin.PluginService.Publish:input_type -> bbgrid.plugin.PublishRequest
	6,  // 8: bbgrid.plugin.PluginService.Register:input_type -> bbgrid.plugin.RegisterRequest
	10, // 9: bbgrid.plugin.PluginService.Execute:input_type -> bbgrid.plugin.ExecuteRequest
	12, // 10: bbgrid.plugin.PluginService.Heartbeat:input_type -> bbgrid.plugin.HeartbeatRequest
	1,  // 11: bbgrid.plugin.PluginService.Subscribe:output_type -> bbgrid.plugin.EventBatch
	5,  // 12: bbgrid.plugin.PluginService.Publish:output_type -> bbgrid.plugin.PublishResponse
	7,  // 13: bbgrid.plugin.PluginService.Register:output_type -> bbgrid.plugin.RegisterResponse
	11, // 14: bbgrid.plugin.PluginService.Execute:output_type -> bbgrid.plugin.ExecuteResponse
	13, // 15: bbgrid.plugin.PluginService.Heartbeat:output_type -> bbgrid.plugin.HeartbeatResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_common_plugin_proto_plugin_proto_init() }
func file_common_plugin_proto_plugin_proto_init() {
	if File_common_plugin_proto_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_plugin_proto_plugin_proto_rawDesc), len(file_common_plugin_proto_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_plugin_proto_plugin_proto_goTypes,
		DependencyIndexes: file_common_plugin_proto_plugin_proto_depIdxs,
		MessageInfos:      file_common_plugin_proto_plugin_proto_msgTypes,
	}.Build()
	File_common_plugin_proto_plugin_proto = out.File
	file_common_plugin_proto_plugin_proto_goTypes = nil
	file_common_plugin_proto_plugin_proto_depIdxs = nil
}
